server {
    listen 80;
    absolute_redirect off;
    port_in_redirect off;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /vibe_tracker/index.html;
    }

    error_page 404 /vibe_tracker/index.html;
    
    location = / {
        return 301 /vibe_tracker/;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
